### ISSUE TITLE
Release version 1.0.2

### ISSUE THREAD

**Issue by eh-am** [4thParty/hubot-dynamic-conversation#10]
I see there was a version bump commit https://github.com/4thParty/hubot-dynamic-conversation/commit/8884e52366d9bf03148ec0b95a81126ad4e60bfd

It would be good to release both here and on npm :)

**Comment by timkinnane** [comment]
Wow, hi @eh-am - I had no idea there were external watchers of this project, but I'm glad you're interested. I've actually been working on a complete refactor (with new features and fully unit-tested) over at https://github.com/timkinnane/hubot-playbook - So you should keep an eye on that. I can't promise anything that will save you right now, but I'm hoping to publish the first stable NPM release within about a week.

**Comment by eh-am** [comment]
hahah, that's the beauty of gh/os :)

awesome, will keep an eye on that, keep up with the good work!
