### ISSUE TITLE
NPM package is out of date.

### ISSUE THREAD

**Issue by JigSawFr** [4thParty/hubot-dynamic-conversation#11]
Hello,
Can you push a new release to npm ?
Actual package is out of date.
Thank you

**Comment by timkinnane** [comment]
Sorry @JigSawFr, support for this package is discontinued. I have a new package called [hubot-playbook](https://github.com/timkinnane/hubot-playbook) that does more and better. It's largely undocumented as yet, but the core functionality is complete and I will be adding docs shortly. I would advise watching the repo, but not using it in production at this stage.
