### ISSUE TITLE
Don't repeat question if an invalid answer is given

### ISSUE THREAD

**Issue by garychapman** [4thParty/hubot-dynamic-conversation#6]
@ngenerio 

- When the user gives an invalid response to a question, we do not want the question to be repeated.

**Comment by ngenerio** [comment]
So for example: the question that demands a `public` or `private` answer, if the user is supposed to type something else other than that, we just skip that question.

**Comment by garychapman** [comment]
We don't want to skip the question, we just don't want the robot to keep giving the question text.

e.g.

Gary: problem
Robot: Is the problem in a [public] or [private] place, or [skip] to continue **<--- original question**
Gary: neither
Robot: I didn't understand that response
Robot: Is the problem in a [public] or [private] place, or [skip] to continue  **<--- DO NOT DISPLAY original question**
Gary: get lost
Robot: I didn't understand that response
Robot: Is the problem in a [public] or [private] place, or [skip] to continue  **<--- DO NOT DISPLAY question**
Gary: public
Robot: Ok, got it. Please describe the problem...
etc...

So instead it should be:

Gary: problem
Robot: Is the problem in a [public] or [private] place, or [skip] to continue **<--- original question**
Gary: neither
Robot: I didn't understand that response
Gary: get lost
Robot: I didn't understand that response
Gary: public
Robot: Ok, got it. Please describe the problem...

**Comment by ngenerio** [comment]
@garychapman I get what you mean.

**Comment by garychapman** [comment]
@ngenerio Works well, but it breaks the fix for https://github.com/4thParty/hubot-dynamic-conversation/issues/7 - now if I give an invalid response for an _attachment_, it goes into a state where it ignores any further input.

**Comment by ngenerio** [comment]
Realized earlier that there was going to be an issue like that because of the refactoring. I jave5 seen it already and working on it.

**Comment by ngenerio** [comment]
@garychapman can you check again with the [fix/question](https://github.com/4thParty/hubot-dynamic-conversation/tree/fix/question) branch!

**Comment by garychapman** [comment]
Thanks, i'll take a look tomorrow and get back to you. Are there any other
open issues you can look at in the meantime?

**Comment by ngenerio** [comment]
I will work on #8.

**Comment by garychapman** [comment]
@ngenerio I have tested https://github.com/4thParty/hubot-dynamic-conversation/tree/fix/question - issue https://github.com/4thParty/hubot-dynamic-conversation/issues/7 is definitely broken.

**Comment by garychapman** [comment]
This is fixed on the fix/question branch.
I think #7 is fixed now too.
