### ISSUE TITLE
Repeat non-required attachment request

### ISSUE THREAD

**Issue by garychapman** [4thParty/hubot-dynamic-conversation#7]
@ngenerio 

When the conversation script requests an attachment with `required: false`, if the user types something (other than 'skip') instead of attaching a file, the script displays the `error` message, but continues to the next question.

Is it possible for the script to NOT continue until the user either adds an attachment or types 'skip'?

**Comment by ngenerio** [comment]
@garychapman Because the message was marked as not ie. `required: false`, we simply move to the next question. The required will make the bot ask the user for an attachment until it is provided.

**Comment by garychapman** [comment]
@ngenerio I think with any `required:false` question, the only conditions that should make the bot move to the next question are either:

- the user supplies a valid value (one of the 'choice' values if `type:text`, or an attachment if `type:attachment`)

or

- user types 'skip'

i.e. the user can 'skip' a `required:false` question, but it still should validate any given response
