### ISSUE TITLE
robot.catchAll doesn't fire after a conversation

### ISSUE THREAD

**Issue by garychapman** [4thParty/hubot-dynamic-conversation#8]
If I define a `catchAll `function as in the example below, it works as expected - when I enter anything other than 'problem' it fires.

However, after having a 'problem' conversation, `catchAll `never fires again.

```
DynamicConversation = require 'hubot-dynamic-conversation'
module.exports = (robot) ->
  dynamic = new DynamicConversation robot

  robot.respond /problem/i, (msg) ->
    robot.logger.info 'hello'
    msg.reply "OK, I can make a maintenance report for you, just answer some questions..."
    maintenanceRequestModel = {
        abortKeyword: 'quit',
        onAbortMessage: 'You cancelled the conversation.',
        onCompleteMessage: 'Thanks for reporting this. I\'ll notify @bm immediately.',
        conversation: [ 
          {
            question: "Is it in a [public] or [private] area?",
            answer: {
            type: "choice",
            options: [
                {
                match: "public",
                valid: true,
                response: "OK you said *public*, next step...",
                value: "public"
                },
                {
                match: "private",
                valid: false,
                response: "Sorry, you will have to find a contractor for private maintenance"
                }
            ]
            },
            required: true,
            error: "Sorry, I don't understand that. Please say [private] or [public] to proceed."
        }
        ]
    }

    dialog = dynamic.start msg, maintenanceRequestModel, (err, msg, dialog) ->
      if err
        robot.logger.error err
      else
        data = dialog.fetch()
        robot.logger.info data
 

  robot.catchAll (msg) ->
    r = new RegExp "^(@?#{robot.alias}:?|#{robot.name})", "i"
    matches = msg.message.text.match(r)
    if matches != null && matches.length > 1
      msg.send "huh?"

    msg.finish()
```

**Comment by garychapman** [comment]
@ngenerio I have noticed that when the bot has stopped responding to `catchAll`, if you start a new conversation and let it time out, `catchAll` will fire again. I wonder if the problem might be with hubot-conversation

**Comment by ngenerio** [comment]
Hmmm...I will check it out. Never faced this issue. I will dig deeper into hubot-conversation but probably be from here too.

**Comment by garychapman** [comment]
Could be related to https://github.com/lmarkus/hubot-conversation/issues/12

**Comment by garychapman** [comment]
I hacked a working solution together by emitting a 'timeout' message to the dialog object in our own 'end' handler.

**Comment by JigSawFr** [comment]
@garychapman hi, i'm running the same problem, can you show me how you handle the problem on your end ? thank you

**Comment by JigSawFr** [comment]
I've tested with the example script "Trade bot", the listener is not removed after the conversation, so catchAll will be not fired anymore :/

**Comment by JigSawFr** [comment]
My bad, npm package is out of date.

**Comment by ahadjithoma** [comment]
@JigSawFr the problem is with this dependency[ lmarkus/hubot-conversation](https://github.com/lmarkus/hubot-conversation). I had exactly the same problem when i was using the hubot-conversation and i solved it like [this](https://github.com/lmarkus/hubot-conversation/pull/20)
